//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب را انتخاب نمائید.
        /// </summary>
        public static string AccountIdRequired {
            get {
                return ResourceManager.GetString("AccountIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام حساب را وارد نمائید.
        /// </summary>
        public static string AccountNameRequired {
            get {
                return ResourceManager.GetString("AccountNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب را وراد نمائید.
        /// </summary>
        public static string AccountNoRequired {
            get {
                return ResourceManager.GetString("AccountNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات روی حساب را انتخاب نمائید.
        /// </summary>
        public static string AccountOprationRequired {
            get {
                return ResourceManager.GetString("AccountOprationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام بانک را وارد نمائید.
        /// </summary>
        public static string BankNameRequired {
            get {
                return ResourceManager.GetString("BankNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد شعبه را وارد نمائید.
        /// </summary>
        public static string BranchCodeRequired {
            get {
                return ResourceManager.GetString("BranchCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شعبه را وارد نمائید.
        /// </summary>
        public static string BranchNameRequired {
            get {
                return ResourceManager.GetString("BranchNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن شعبه را وارد نمائید.
        /// </summary>
        public static string BranchPhoneRequired {
            get {
                return ResourceManager.GetString("BranchPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور جدید و تکرار آن مطابقت ندارند.
        /// </summary>
        public static string ConfirmNewPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور و تکرار آن مطابقت ندارند.
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه مستمر را وارد کنید.
        /// </summary>
        public static string ContinousSettleRequired {
            get {
                return ResourceManager.GetString("ContinousSettleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد مشتری را وارد کنید.
        /// </summary>
        public static string CustomerCodeRequired {
            get {
                return ResourceManager.GetString("CustomerCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واریز کننده را وارد کنید.
        /// </summary>
        public static string CustomerRequired {
            get {
                return ResourceManager.GetString("CustomerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد اقتصادی را وارد کنید.
        /// </summary>
        public static string EconomicCodeRequired {
            get {
                return ResourceManager.GetString("EconomicCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام می تواند حداکثر 50 کاراکتر باشد.
        /// </summary>
        public static string FNameLength {
            get {
                return ResourceManager.GetString("FNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام را وارد کنید.
        /// </summary>
        public static string FNameRequired {
            get {
                return ResourceManager.GetString("FNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی می تواند حداکثر 50 کاراکتر باشد.
        /// </summary>
        public static string LNameLength {
            get {
                return ResourceManager.GetString("LNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی را وارد کنید.
        /// </summary>
        public static string LNameRequired {
            get {
                return ResourceManager.GetString("LNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی را وارد کنید.
        /// </summary>
        public static string NationalCodeRequired {
            get {
                return ResourceManager.GetString("NationalCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور جدید را وارد کنید.
        /// </summary>
        public static string NewPasswordRequired {
            get {
                return ResourceManager.GetString("NewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور جاری را وارد کنید.
        /// </summary>
        public static string OldPasswordRequired {
            get {
                return ResourceManager.GetString("OldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چارت سازمانی را انتخاب نمائید.
        /// </summary>
        public static string OrganazationChartIdRequired {
            get {
                return ResourceManager.GetString("OrganazationChartIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور را وارد کنید.
        /// </summary>
        public static string PassRequired {
            get {
                return ResourceManager.GetString("PassRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور باید حداقل 6 کاراکتر باشد.
        /// </summary>
        public static string PasswordMinimumLength {
            get {
                return ResourceManager.GetString("PasswordMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ واریز را وارد کنید.
        /// </summary>
        public static string PriceRequired {
            get {
                return ResourceManager.GetString("PriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش را تعیین کنید.
        /// </summary>
        public static string RoleRequired {
            get {
                return ResourceManager.GetString("RoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان واریز را وارد کنید.
        /// </summary>
        public static string SettleTitleRequired {
            get {
                return ResourceManager.GetString("SettleTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان را وارد نمائید.
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری می تواند حداکثر 20 کاراکتر باشد.
        /// </summary>
        public static string UserNameLength {
            get {
                return ResourceManager.GetString("UserNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری را وارد کنید.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
    }
}
