// <auto-generated />
namespace SampleProject.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ttt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ttt));
        
        string IMigrationMetadata.Id
        {
            get { return "201307151020302_ttt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
