// <auto-generated />
namespace SampleProject.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class rrr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rrr));
        
        string IMigrationMetadata.Id
        {
            get { return "201307220819149_rrr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
